### PR TITLE
Final code cleanup

### PR DESCRIPTION
**Pull request by Kaolinnite**
- Added return lines so the robot stops after encountering the flag; removed some unnecessary lines
- Cleaned up some of the code and documentation

This is the first patch of several, depending if I have time. Comment on some other suggestions you have

### CODE REVIEW

**Comment by Kaolinnite** [comment]
If you viewed this after getting emailed, sorry but this is still unfinished

**Comment by deswa7310** [comment]
The edits you've made are great and it does look a lot cleaner now! The commenting is much better and I really like your idea of killing the program once the flag is reached. That's a merge from me dawg

**Comment by Kaolinnite** [comment]
I'm gonna add more tonight if I have time, else I can do more tomorrow

**Comment by deswa7310** [comment]
I've created a new pull request with some additional edits. I'm pretty sure our code is almost in its final version.

**Pull request merged**
