### PR TITLE
Update robot.cpp

### LINKED ISSUE #27: Challenge Code Completion
Now that a completion code base is uploaded, all that remains is code optimizations and combining core and completion into one doc and finding a way for choosing between core, completion, and challenge. 

However, if you choose to, challenge is also available. Keep in mind that the deadline is next Friday - ideally we need to have everything prepped before then. We'll also have several tests and a comp assignment due that week (at least if you are taking those classes). So keep that in mind and don't overload yourselves.

### LINKED ISSUE #28: Code Optimisations
Now that the base core and completion code is uploaded, we can move onto submission. Here are the main things needed:
1. All versions need to be on one doc. It can work on every single version without input, or prompt the user
2. Every function needs to be shorter than 80 operators (i.e. lines ending with semicolons)
3. Debugging. If you can break the code, do it
If you can think of anything else, don't hesitate to add. If you come up with a better method for the robot, create a pull request. All that's needed is for everything to be done by Friday 19.

### LINKED ISSUE #29: optimisation
hey team! so assuming we are all happy with the core and completion code so far, I'll make a start on optimizing the codes and seeing if we can make it better etc. i know as engineering students we can get busy, but if anyone is available to optimise code with me that would be great! just msg me on discord or the group chat and yeah

### PR DESCRIPTION
**Pull request by deswa7310**
Added some more minor documentation edits.
- Updated semicolon count.
- Made vGo static too.
- Updated some comments.
- Note: methods and functions are slightly different. Methods act on the data within objects passed to them (Java only uses methods) whereas functions just act on the data passed to them. Since we aren't using objects or classes, we are only using functions.

### CODE REVIEW

**Comment by deswa7310** [comment]
Also lowered the count to 10 for black pixels required to detect the flag, as it was overshooting it on the challenge maze.

**Review by Kaolinnite — APPROVED** [review]
Code works as usual, no basic errors found while tested. No other documentation comments to suggest from me

**Comment by Kaolinnite** [comment]
I'm going to merge this in one hour if no one has any objections

**Comment by deswa7310** [comment]
I think we're good to go.

**Review by modishiv — APPROVED** [review]
from what ive seen i feel like we are ready to go and I approve ! :)

**Comment by Jayman874** [comment]
Ive tested the code multiple times and everything seems good to go

**Comment by Kaolinnite** [comment]
Deleting branch now

**Pull request merged**
