### PR TITLE
Update robot.cpp

### PR DESCRIPTION
**Pull request by Jayman874**
Added base code for core. Error calculation is not working yet

### CODE REVIEW

**Comment by Kaolinnite** [comment]
Before we merge, I'd like an explanation on how the code works and some comments on what each operator is doing

**Comment by Jayman874** [comment]
Added comments to my code

**Comment by deswa7310** [comment]
Is it better to merge now then suggest edits, or suggest edits before merging?

**Comment by Kaolinnite** [comment]
If you have an edit that can be implemented quickly like a documentation, then suggest it before merging so its implemented immediately. If it's an idea that will change how the code works or is longer than two operators for example, it's better to merge now and edit the master branch with your idea.

**Comment by Kaolinnite** [comment]
As this edit is now merged, this branch will be deleted

**Pull request merged**
